#!/usr/bin/env python3
"""Turn every ```rust block under doc/ into a test.

The README's blocks are compiled as doctests because lib.rs includes
it. Nothing compiled the guide, the architecture notes or the security
model, so their code was prose that happened to look like Rust -- and
prose does not fail a build. A README claim that had been false for
months was found this way; these files had the same exposure.

Generates `crates/oxml/tests/doc_examples.rs`, one `#[test]` per block,
named after the file and line it came from so a failure points at the
document to fix. Blocks fenced ```rust,ignore are skipped and counted.
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOC = ROOT / "doc"
OUT = ROOT / "crates" / "oxml" / "tests" / "doc_examples.rs"

HEADER = """// SPDX-License-Identifier: MIT OR Apache-2.0
// Copyright (c) 2026 oxml. All rights reserved.
//
// @generated by scripts/generate-doc-tests.py -- do not edit.
//
// Each test is one ```rust block from a file under doc/. Edit the
// document, then re-run the script. CI regenerates this file and fails
// if the result differs from what is committed.

//! Code blocks from `doc/`, compiled and run.

#![allow(unused_variables, unused_imports, clippy::all, clippy::pedantic)]
"""


def blocks(path: pathlib.Path):
    """Yield (line number, source, ignored) for each rust fence."""
    lines = path.read_text().splitlines()
    current, start, ignored = None, 0, False
    for number, line in enumerate(lines, 1):
        fence = line.strip()
        if current is None and fence.startswith("```rust"):
            current, start = [], number
            ignored = "ignore" in fence or "no_run" in fence
        elif current is not None and fence == "```":
            yield start, "\n".join(current), ignored
            current = None
        elif current is not None:
            current.append(line)


def main() -> int:
    parts = [HEADER]
    total = skipped = 0
    for path in sorted(DOC.rglob("*.md")):
        for line, source, ignored in blocks(path):
            total += 1
            if ignored:
                skipped += 1
                continue
            name = re.sub(r"[^a-z0-9]+", "_", path.relative_to(DOC).as_posix().lower())
            body = "\n".join(f"    {l}" for l in source.splitlines())
            parts.append(
                f"/// From `doc/{path.relative_to(DOC).as_posix()}`, line {line}.\n"
                f"#[test]\n"
                f"fn {name.strip('_')}_line_{line}() {{\n{body}\n}}\n"
            )
    if total == 0:
        sys.exit("found no rust blocks under doc/ -- the script is not working")

    OUT.write_text("\n".join(parts))
    print(f"{total - skipped} tests generated from {total} blocks ({skipped} ignored)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
